Widecare/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', LoginView.as_view(), name='login'),
    url(r'^accounts/logout/', LogoutView.as_view(next_page=reverse_lazy('homepage')), name='logout'),
    url(r'^hr/', include('hr.urls')),
    url(r'^$', views.index, name='homepage'),
    url(r'^$', views.index, name='homepage'),
]

hr/urls.py
from django.conf.urls import url
from .views import *

app_name = 'hr'

urlpatterns = [
    url(r'^$', index, name='index'),

    url(r'^position/add/$', PositionAdd.as_view(), name='position_add'),
    url(r'^position/(?P<position_id>[0-9]+)/delete/$', PositionDelete.as_view(), name='position_delete'),
    url(r'^position/(?P<position_id>[0-9]+)/edit/$', PositionEdit.as_view(), name='position_edit'),
    url(r'^position/list/$', PositionList.as_view(), name='position_list'),
    url(r'^position/(?P<position_id>[0-9]+)/detail/$', PositionDetail.as_view(), name='position_detail'),

    url(r'^staff/add/$', StaffAdd.as_view(), name='staff_add'),
    url(r'^staff/(?P<staff_id>[0-9]+)/delete/$', StaffDelete.as_view(), name='staff_delete'),
    url(r'^staff/(?P<staff_id>[0-9]+)/edit/$', StaffEdit.as_view(), name='staff_edit'),
    url(r'^staff/list/$', StaffList.as_view(), name='staff_list'),
    url(r'^staff/(?P<staff_id>[0-9]+)/detail/$', StaffDetail.as_view(), name='staff_detail'),
]

hr/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Position(models.Model):
    name = models.CharField(max_length=20, verbose_name='岗位名称')
    description = models.TextField(verbose_name='岗位描述')
    requirement = models.TextField(verbose_name='任职要求')
    location = models.CharField(max_length=20, verbose_name='工作地点')
    salary = models.CharField(max_length=20, verbose_name='薪资范围')
    is_on = models.BooleanField(verbose_name='启用', default=True)
    comment = models.TextField(blank=True, verbose_name='备注')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('hr:position_detail', args=str(self.id))

    class Meta:
        ordering = ['name']


class Staff(models.Model):
    DP_CHOICES = ((0, '财务'), (1, '服务'), (2, '销售'), (3, '人事'),)
    SEX_CHOICES = (('M', '男'), ('F', '女'),)
    name_en = models.CharField(max_length=20, verbose_name='Name')
    name_cn = models.CharField(max_length=20, verbose_name='姓名')
    sex = models.CharField(max_length=5, verbose_name='性别', default='M', choices=SEX_CHOICES)
    department = models.IntegerField(verbose_name='部门', choices=DP_CHOICES)
    position = models.ForeignKey(Position, verbose_name='职位')
    email = models.EmailField()
    cellphone = models.CharField(max_length=20, verbose_name='手机')
    is_on = models.BooleanField(verbose_name='在职', default=True)
    phone = models.CharField(blank=True, max_length=20, verbose_name='电话')
    address = models.CharField(blank=True, max_length=100, verbose_name='住址')
    qq = models.CharField(blank=True, max_length=20, verbose_name='QQ')
    wechat = models.CharField(blank=True, max_length=20, verbose_name='微信')
    resume = models.FileField(blank=True, verbose_name='简历')
    comment = models.TextField(blank=True, verbose_name='备注')

    def __str__(self):
        return self.name_en

    def get_absolute_url(self):
        return reverse('hr:staff_detail', args=str(self.id))

    class Meta:
        ordering = ['name_en']

Widecare/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    return render(request, 'index.html')

hr/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView

from .models import *


# Create your views here.

def index(request):
    return render(request, 'hr/index.html')




class PositionAdd(CreateView):
    model = Position
    fields = ['name', 'description', 'requirement', 'location', 'salary', 'is_on']
    success_url = reverse_lazy('hr:position_list')


class PositionDelete(DeleteView):
    model = Position
    success_url = reverse_lazy('hr:position_list')
    pk_url_kwarg = 'position_id'


class PositionEdit(UpdateView):
    model = Position
    fields = ['name', 'description', 'requirement', 'location', 'salary', 'is_on', 'comment']
    pk_url_kwarg = 'position_id'


class PositionList(ListView):
    model = Position
    context_object_name = 'position_list'


class PositionDetail(DetailView):
    model = Position
    pk_url_kwarg = 'position_id'

    def get_context_data(self, **kwargs):
        context = super(PositionDetail, self).get_context_data(**kwargs)
        context['staff_list'] = Staff.objects.all()
        return context


class StaffAdd(CreateView):
    model = Staff
    fields = ['name_en', 'name_cn', 'sex', 'department', 'position', 'email', 'cellphone', 'is_on']


class StaffDelete(DeleteView):
    model = Staff
    success_url = reverse_lazy('hr:staff_list')
    pk_url_kwarg = 'staff_id'


class StaffEdit(UpdateView):
    model = Staff
    fields = ['name_en', 'name_cn', 'sex', 'department', 'position', 'email', 'cellphone', 'is_on', 'phone', 'address',
              'qq', 'wechat']
    pk_url_kwarg = 'staff_id'


class StaffList(ListView):
    model = Staff


class StaffDetail(DetailView):
    model = Staff
    pk_url_kwarg = 'staff_id'

hr/templates/hr/index.html
<h1>HR homepage</h1>

<ul>
    <li><a href="{% url 'hr:position_list' %}">Position</a></li>
    <li><a href="{% url 'hr:staff_list' %}">Staff</a></li>
</ul>

hr/templates/hr/position_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <h1>Are you sure you want to delete <strong>"{{ object }}"</strong>?</h1>
    <ul>
        <li>{{ object.description }}</li>
        <li>{{ object.requirement }}</li>
        <li>{{ object.location }}</li>
        <li>{{ object.salary }}</li>
        <li>{{ object.is_on }}</li>
        <li>{{ object.comment }}</li>
    </ul>
    <input type="submit" value="Confirm"/>
</form>

hr/templates/hr/position_detail.html
<ul>
    <li>{{ object.id }}</li>
    <li>{{ object.name }}</li>
    <li>{{ object.description }}</li>
    <li>{{ object.requirement }}</li>
    <li>{{ object.salary }}</li>
    <li>{{ object.location }}</li>
    <li>{{ object.comment }}</li>
</ul>

<table border="1">
    <tr>
        <td>ID</td>
        <td>Name_EN</td>
        <td>Name_CN</td>
        <td>Sex</td>
    </tr>
    {% for staff in staff_list %}
        <tr>
            <td>{{ staff.id }}</td>
            <td>{{ staff.name_en }}</td>
            <td>{{ staff.name_cn }}</td>
            <td>{{ staff.sex }}</td>
        </tr>
    {% endfor %}
</table>

hr/templates/hr/position_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Save and Add Another" name="Save and Add Another">
    <input type="submit" value="Save and Edit" name="Save and Edit">
    <input type="submit" value="Save" name="Save">
</form>

hr/templates/hr/position_list.html
<h1>Here are all positions:</h1>
{% if position_list %}
    <table border="1">
        {% for position in position_list %}
            <tr>
                <td><a href="{% url 'hr:position_detail' position.id %}">{{ position.name }}</a></td>
                <td><a href="{% url 'hr:position_edit' position.id %}">edit</a> -- <a
                        href="{% url 'hr:position_delete' position.id %}">delete</a></td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h2>No position</h2>
{% endif %}
<h1><a href="{% url 'hr:position_add' %}">Add A Position</a></h1>

hr/templates/hr/staff_detail.html
<ul>
    <li>{{ object.id }}</li>
    <li>{{ object.name_en }}</li>
    <li>{{ object.name_cn }}</li>
    <li>{{ object.sex }}</li>
    <li>{{ object.department }}</li>
    <li>{{ object.position }}</li>
    <li>{{ object.email }}</li>
    <li>{{ object.cellphone }}</li>
</ul>

hr/templates/hr/staff_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Save and Add Another">
    <input type="submit" value="Save and Edit">
    <input type="submit" value="Save">
</form>

hr/templates/hr/staff_list.html
<h1>Here are all staffs:</h1>
{% if object_list %}
    <table border="1">
        {% for staff in object_list %}
            <tr>
                <td><a href="{% url 'hr:staff_detail' staff.id %}">{{ staff.name_en }}</a></td>
                <td><a href="{% url 'hr:staff_edit' staff.id %}">edit</a> -- <a
                        href="{% url 'hr:staff_delete' staff.id %}">delete</a></td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h2>No staff</h2>
{% endif %}
<h1><a href="{% url 'hr:staff_add' %}">Add A staff</a></h1>

templates/index.html
<ul>
    <li><a href="{% url 'hr:index' %}">HR</a></li>
</ul>

<a href="{% url 'logout' %}">Logout</a>